function Grad_Sigma_V = Grad_Sigma_V_FT(X,alpha)
%Grad_Sigma_V
%    Grad_Sigma_V = Grad_Sigma_V(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024-09-26 11:06:18

x1 = X(1,:);
x2 = X(2,:);
% x3 = X(3,:);
% x4 = X(4,:);
% x5 = X(5,:);
% x6 = X(6,:);
% x7 = X(7,:);
% x8 = X(8,:);
% x9 = X(9,:);
% x10 = X(10,:);
% x11 = X(11,:);
% x12 = X(12,:);

%% test for LQR-based NN basis
% Sigma_V = 1/(alpha+1)*[x1*x11, x4*x11, x8*x11, x11^2, x2*x10, x3*x10, x7*x10, x10^2, x3*x6, x6^2, x9*x12, x12^2].^((alpha+1)/1);
% Grad_Sigma_V = [x11, 0, 0, 0, 0, 0, 0, 0, 0, 0, x1, 0; % x1*x11
%                 0, 0, 0, x11, 0, 0, 0, 0, 0, 0, x4, 0; % x4*x11
%                 0, 0, 0, 0, 0, 0, 0, x11, 0, 0, x8, 0; % x8*x11
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*x11, 0; % x11^2
%                 0, x10, 0, 0, 0, 0, 0, 0, 0, x2, 0, 0; % x2*x10
%                 0, 0, 0, 0, x10, 0, 0, 0, 0, x5, 0, 0; % x3*x10
%                 0, 0, 0, 0, 0, 0, x10, 0, 0, x7, 0, 0; % x7*x10
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*x10, 0, 0; % x10^2
%                 0, 0, x6, 0, 0, x3, 0, 0, 0, 0, 0, 0; % x3*x6
%                 0, 0, 0, 0, 0, 2*x6, 0, 0, 0, 0, 0, 0; % x6^2
%                 0, 0, 0, 0, 0, 0, 0, 0, x12, 0, 0, x9; % x9*x12
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*x12; % x12^2
% ];
% Sigma_V = 1/(alpha+1)*[x1*x11, x4*x11, x8*x11, x11^2, x2*x10, x3*x10, x7*x10, x10^2, x3*x6, x6^2, x9*x12, x12^2].^((alpha+1)/1);
% Grad_Sigma_V = [x11*sum(abs(x1*x11)^alpha)*sign(x1*x11), 0, 0, 0, 0, 0, 0, 0, 0, 0, x1*sum(abs(x1*x11)^alpha)*sign(x1*x11), 0; % x1*x11
%                 0, 0, 0, x11*sum(abs(x4*x11)^alpha)*sign(x4*x11), 0, 0, 0, 0, 0, 0, x4*sum(abs(x4*x11)^alpha)*sign(x4*x11), 0; % x4*x11
%                 0, 0, 0, 0, 0, 0, 0, x11*sum(abs(x8*x11)^alpha)*sign(x8*x11), 0, 0, x8*sum(abs(x8*x11)^alpha)*sign(x8*x11), 0; % x8*x11
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*x11*sum(abs(x11^2)^alpha)*sign(x11^2), 0; % x11^2
%                 0, x10*sum(abs(x2*x10)^alpha)*sign(x2*x10), 0, 0, 0, 0, 0, 0, 0, x2*sum(abs(x2*x10)^alpha)*sign(x2*x10), 0, 0; % x2*x10
%                 0, 0, 0, 0, x10*sum(abs(x5*x10)^alpha)*sign(x5*x10), 0, 0, 0, 0, x5*sum(abs(x5*x10)^alpha)*sign(x5*x10), 0, 0; % x3*x10
%                 0, 0, 0, 0, 0, 0, x10*sum(abs(x7*x10)^alpha)*sign(x7*x10), 0, 0, x7*sum(abs(x7*x10)^alpha)*sign(x7*x10), 0, 0; % x7*x10
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*x10*sum(abs(x10^2)^alpha)*sign(x10^2), 0, 0; % x10^2
%                 0, 0, x6*sum(abs(x3*x6)^alpha)*sign(x3*x6), 0, 0, x3*sum(abs(x3*x6)^alpha)*sign(x3*x6), 0, 0, 0, 0, 0, 0; % x3*x6
%                 0, 0, 0, 0, 0, 2*x6*sum(abs(x6^2)^alpha)*sign(x6^2), 0, 0, 0, 0, 0, 0; % x6^2
%                 0, 0, 0, 0, 0, 0, 0, 0, x12*sum(abs(x9*x12)^alpha)*sign(x9*x12), 0, 0, x9*sum(abs(x9*x12)^alpha)*sign(x9*x12); % x9*x12
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*x12*x6*sum(abs(x12^2)^alpha)*sign(x12^2); % x12^2
% ];
% Grad_Sigma_V = [(abs(x1)^alpha)*sign(x1), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0; % x1*x11
%                 0, 0, 0, (abs(x4)^alpha)*sign(x4), 0, 0, 0, 0, 0, 0, 0, 0; % x4*x11
%                 0, 0, 0, 0, 0, 0, 0, (abs(x8)^alpha)*sign(x8), 0, 0, 0, 0; % x8*x11
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (abs(x11)^alpha)*sign(x11), 0; % x11^2
%                 0, (abs(x2)^alpha)*sign(x2), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0; % x2*x10
%                 0, 0, 0, 0, (abs(x5)^alpha)*sign(x5), 0, 0, 0, 0, 0, 0, 0; % x3*x10
%                 0, 0, 0, 0, 0, 0, (abs(x7)^alpha)*sign(x7), 0, 0, 0, 0, 0; % x7*x10
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, (abs(x10)^alpha)*sign(x10), 0, 0; % x10^2
%                 0, 0, (abs(x3)^alpha)*sign(x3), 0, 0, 0, 0, 0, 0, 0, 0, 0; % x3*x6
%                 0, 0, 0, 0, 0, (abs(x6)^alpha)*sign(x6), 0, 0, 0, 0, 0, 0; % x6^2
%                 0, 0, 0, 0, 0, 0, 0, 0, (abs(x9)^alpha)*sign(x9), 0, 0, 0; % x9*x12
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (abs(x12)^alpha)*sign(x12); % x12^2
% ];
% Grad_Sigma_V = [x11*(abs(x1*x11)^alpha)*sign(x1*x11), 0, 0, 0, 0, 0, 0, 0, 0, 0, x1*(abs(x1*x11)^alpha)*sign(x1*x11), 0; % x1*x11
%                 0, 0, 0, x11*(abs(x4*x11)^alpha)*sign(x4*x11), 0, 0, 0, 0, 0, 0, x4*(abs(x4*x11)^alpha)*sign(x4*x11), 0; % x4*x11
%                 0, 0, 0, 0, 0, 0, 0, x11*(abs(x8*x11)^alpha)*sign(x8*x11), 0, 0, x8*(abs(x8*x11)^alpha)*sign(x8*x11), 0; % x8*x11
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*x11*(abs(x11)^alpha)*sign(x11), 0; % x11^2
%                 0, x10*(abs(x2*x10)^alpha)*sign(x2*x10), 0, 0, 0, 0, 0, 0, 0, x2*(abs(x2*x10)^alpha)*sign(x2*x10), 0, 0; % x2*x10
%                 0, 0, 0, 0, x10*(abs(x5*x10)^alpha)*sign(x5*x10), 0, 0, 0, 0, x5*(abs(x5*x10)^alpha)*sign(x5*x10), 0, 0; % x3*x10
%                 0, 0, 0, 0, 0, 0, x10*(abs(x7*x10)^alpha)*sign(x7*x10), 0, 0, x7*(abs(x7*x10)^alpha)*sign(x7*x10), 0, 0; % x7*x10
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*x10*(abs(x10)^alpha)*sign(x10), 0, 0; % x10^2
%                 0, 0, x6*(abs(x3*x6)^alpha)*sign(x3*x6), 0, 0, x3*(abs(x3*x6)^alpha)*sign(x3*x6), 0, 0, 0, 0, 0, 0; % x3*x6
%                 0, 0, 0, 0, 0, 2*x6*(abs(x6)^alpha)*sign(x6), 0, 0, 0, 0, 0, 0; % x6^2
%                 0, 0, 0, 0, 0, 0, 0, 0, x12*(abs(x9*x12)^alpha)*sign(x9*x12), 0, 0, x9*(abs(x9*x12)^alpha)*sign(x9*x12); % x9*x12
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*x12*(abs(x12)^alpha)*sign(x12); % x12^2
% ];
% Grad_Sigma_V = [(abs(x11)^alpha)*sign(x11), 0, 0, 0, 0, 0, 0, 0, 0, 0, (abs(x1)^alpha)*sign(x1), 0; % x1*x11
%                 0, 0, 0, (abs(x11)^alpha)*sign(x11), 0, 0, 0, 0, 0, 0, (abs(x4)^alpha)*sign(x4), 0; % x4*x11
%                 0, 0, 0, 0, 0, 0, 0, (abs(x11)^alpha)*sign(x11), 0, 0, (abs(x8)^alpha)*sign(x8), 0; % x8*x11
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*(abs(x11)^alpha)*sign(x11), 0; % x11^2
%                 0, (abs(x10)^alpha)*sign(x10), 0, 0, 0, 0, 0, 0, 0, (abs(x2)^alpha)*sign(x2), 0, 0; % x2*x10
%                 0, 0, 0, 0, (abs(x10)^alpha)*sign(x10), 0, 0, 0, 0, (abs(x5)^alpha)*sign(x5), 0, 0; % x3*x10
%                 0, 0, 0, 0, 0, 0, (abs(x10)^alpha)*sign(x10), 0, 0, (abs(x7)^alpha)*sign(x7), 0, 0; % x7*x10
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*(abs(x10)^alpha)*sign(x10), 0, 0; % x10^2
%                 0, 0, (abs(x6)^alpha)*sign(x6), 0, 0, (abs(x3)^alpha)*sign(x3), 0, 0, 0, 0, 0, 0; % x3*x6
%                 0, 0, 0, 0, 0, 2*(abs(x6)^alpha)*sign(x6), 0, 0, 0, 0, 0, 0; % x6^2
%                 0, 0, 0, 0, 0, 0, 0, 0, (abs(x12)^alpha)*sign(x12), 0, 0, (abs(x9)^alpha)*sign(x9); % x9*x12
%                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2*(abs(x12)^alpha)*sign(x12); % x12^2
% ];

Grad_Sigma_V = [(abs(x1)^alpha)*sign(x1), 0;
                0, (abs(x2)^alpha)*sign(x2);
                (abs(x1)^alpha)*sign(x1), (abs(x2)^alpha)*sign(x2)];
end




























